Repository 2011Scape/game, pull requests merged in 2023-07, with the labels that each got.

#403 refactor: changed naming from start to default in animations
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/Animations.kt
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/CombatAnimation.kt
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/CombatConfigs.kt
Labels: refactor

#405 bug: enhancements and fixes for a variety of reported issues.
  .gitignore
  data/cfg/doors/single-doors.json
  data/cfg/objs.yml
  data/packets.yml
  game/plugins/src/main/kotlin/gg/rsmod/plugins/api/cfg/Objs.kt
  game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/lumbridge_celler.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_12950.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/varrock/varrock_stairs.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/scripts/impl/ImpCombatScript.kt
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/lamps/lamp_interface.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/PawnExt.kt
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/teleports/teleport_spells.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/identitykit/character_customization.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/abyss.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/bank_locs/bank_booths.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/quests/quest_tab.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/randoms/random_event_handler.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/runetek5.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/fishing/fishing.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/level_up.plugin.kts
  game/src/main/kotlin/gg/rsmod/game/action/PlayerDeathAction.kt
  game/src/main/kotlin/gg/rsmod/game/message/MessageEncoderSet.kt
  game/src/main/kotlin/gg/rsmod/game/message/encoder/MusicEffectEncoder.kt
  game/src/main/kotlin/gg/rsmod/game/message/impl/MusicEffectMessage.kt
  game/src/main/kotlin/gg/rsmod/game/model/Appearance.kt
  game/src/main/kotlin/gg/rsmod/game/model/World.kt
  game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt
  game/src/main/kotlin/gg/rsmod/game/model/timer/Timers.kt
  game/src/main/kotlin/gg/rsmod/game/service/game/ObjectMetadataService.kt
  game/src/main/kotlin/gg/rsmod/game/service/serializer/PlayerSerializerService.kt
Labels: bug, enhancement

#407 hotfix: patched invincibility bug and various game breaking bugs.
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/morytania/temple_of_saradomin.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/critters/cave_bug_lvl_6.plugin.kts
  game/src/main/kotlin/gg/rsmod/game/action/PawnPathAction.kt
  game/src/main/kotlin/gg/rsmod/game/action/PlayerDeathAction.kt
  game/src/main/kotlin/gg/rsmod/game/message/MessageEncoderSet.kt
  game/src/main/kotlin/gg/rsmod/game/model/attr/Attributes.kt
  game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt
Labels: bug

#408 feat: added destroy item interface
  game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/QueueTaskExt.kt
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/destroy_item.plugin.kts
  game/src/main/kotlin/gg/rsmod/game/message/handler/IfButton1Handler.kt
Labels: content
