Repository 2011Scape/game, pull requests merged in 2025-03, with the labels that each got.

#578 Instances
  data/packets.yml
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts
  game/src/main/kotlin/gg/rsmod/game/message/MessageEncoderSet.kt
  game/src/main/kotlin/gg/rsmod/game/message/encoder/RebuildRegionEncoder.kt
  game/src/main/kotlin/gg/rsmod/game/message/impl/RebuildRegionMessage.kt
  game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt
  game/src/main/kotlin/gg/rsmod/game/model/instance/InstancedMapAllocator.kt
  game/src/main/kotlin/gg/rsmod/game/model/instance/InstancedMapConfiguration.kt
  game/src/main/kotlin/gg/rsmod/game/sync/task/NpcSynchronizationTask.kt
  game/src/main/kotlin/gg/rsmod/game/sync/task/PlayerPreSynchronizationTask.kt
Labels: enhancement, QA Testing

#581 Change combat level message for max combat from lvl 126 to 138
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/level_up.plugin.kts
Labels: bug

#579 Add MinimapToggle packet support
  data/packets.yml
  game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt
  game/src/main/kotlin/gg/rsmod/game/message/MessageEncoderSet.kt
  game/src/main/kotlin/gg/rsmod/game/message/encoder/MinimapToggleEncoder.kt
  game/src/main/kotlin/gg/rsmod/game/message/impl/MinimapToggleMessage.kt
Labels: enhancement, QA Approval
