Repository 2011Scape/game, pull requests merged in 2025-01, with the labels that each got.

#569 Add Friendlist / Private Messaging / Ignorelist
  data/packets.yml
  game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PawnExt.kt
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/friends/friendlist.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/friends/ignorelist.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/gameframe/settings_tab.plugin.kts
  game/src/main/kotlin/gg/rsmod/game/message/MessageDecoderSet.kt
  game/src/main/kotlin/gg/rsmod/game/message/MessageEncoderSet.kt
  game/src/main/kotlin/gg/rsmod/game/message/decoder/ChatFilterDecoder.kt
  game/src/main/kotlin/gg/rsmod/game/message/decoder/FriendListAddDecoder.kt
  game/src/main/kotlin/gg/rsmod/game/message/decoder/FriendListDeleteDecoder.kt
  game/src/main/kotlin/gg/rsmod/game/message/decoder/IgnoreListAddDecoder.kt
  game/src/main/kotlin/gg/rsmod/game/message/decoder/IgnoreListDeleteDecoder.kt
  game/src/main/kotlin/gg/rsmod/game/message/decoder/MessagePrivateDecoder.kt
  game/src/main/kotlin/gg/rsmod/game/message/encoder/FriendListLoadedEncoder.kt
  game/src/main/kotlin/gg/rsmod/game/message/encoder/MessagePrivateReceivedEncoder.kt
  game/src/main/kotlin/gg/rsmod/game/message/encoder/MessagePrivateSentEncoder.kt
  game/src/main/kotlin/gg/rsmod/game/message/encoder/SetPrivateChatFilterEncoder.kt
  game/src/main/kotlin/gg/rsmod/game/message/encoder/SetPublicTradeChatFilterEncoder.kt
  game/src/main/kotlin/gg/rsmod/game/message/encoder/UpdateFriendListEncoder.kt
  game/src/main/kotlin/gg/rsmod/game/message/encoder/UpdateIgnoreListEncoder.kt
  game/src/main/kotlin/gg/rsmod/game/message/handler/ChatFilterHandler.kt
  game/src/main/kotlin/gg/rsmod/game/message/handler/FriendListAddHandler.kt
  game/src/main/kotlin/gg/rsmod/game/message/handler/FriendListDeleteHandler.kt
  game/src/main/kotlin/gg/rsmod/game/message/handler/IgnoreListAddHandler.kt
  game/src/main/kotlin/gg/rsmod/game/message/handler/IgnoreListDeleteHandler.kt
  game/src/main/kotlin/gg/rsmod/game/message/handler/MessagePrivateHandler.kt
  game/src/main/kotlin/gg/rsmod/game/message/impl/ChatFilterMessage.kt
  game/src/main/kotlin/gg/rsmod/game/message/impl/FriendListAddMessage.kt
  game/src/main/kotlin/gg/rsmod/game/message/impl/FriendListDeleteMessage.kt
  game/src/main/kotlin/gg/rsmod/game/message/impl/FriendListLoadedMessage.kt
  game/src/main/kotlin/gg/rsmod/game/message/impl/IgnoreListAddMessage.kt
  game/src/main/kotlin/gg/rsmod/game/message/impl/IgnoreListDeleteMessage.kt
  game/src/main/kotlin/gg/rsmod/game/message/impl/MessagePrivateMessage.kt
  game/src/main/kotlin/gg/rsmod/game/message/impl/MessagePrivateReceivedMessage.kt
  game/src/main/kotlin/gg/rsmod/game/message/impl/MessagePrivateSentMessage.kt
  game/src/main/kotlin/gg/rsmod/game/message/impl/SetPrivateChatFilterMessage.kt
  game/src/main/kotlin/gg/rsmod/game/message/impl/SetPublicTradeChatFilterMessage.kt
  game/src/main/kotlin/gg/rsmod/game/message/impl/UpdateFriendListMessage.kt
  game/src/main/kotlin/gg/rsmod/game/message/impl/UpdateIgnoreListMessage.kt
  game/src/main/kotlin/gg/rsmod/game/model/ChatFilterType.kt
  game/src/main/kotlin/gg/rsmod/game/model/Friend.kt
  game/src/main/kotlin/gg/rsmod/game/model/IgnoredPlayer.kt
  game/src/main/kotlin/gg/rsmod/game/model/World.kt
  game/src/main/kotlin/gg/rsmod/game/model/attr/Attributes.kt
  game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt
  game/src/main/kotlin/gg/rsmod/game/plugin/KotlinPlugin.kt
  game/src/main/kotlin/gg/rsmod/game/plugin/PluginRepository.kt
  game/src/main/kotlin/gg/rsmod/game/service/log/LoggerService.kt
  game/src/main/kotlin/gg/rsmod/game/service/serializer/json/JsonPlayerSaveData.kt
  game/src/main/kotlin/gg/rsmod/game/service/serializer/json/JsonPlayerSerializer.kt
  net/src/main/kotlin/gg/rsmod/net/codec/game/GamePacketEncoder.kt
Labels: enhancement, QA Testing

#571 Logger for Private Messages
  .gitignore
  build.gradle
  game.yml
  game/src/main/kotlin/gg/rsmod/game/message/handler/MessagePrivateHandler.kt
  game/src/main/kotlin/gg/rsmod/game/service/log/FileLoggerService.kt
  game/src/main/kotlin/gg/rsmod/game/service/log/LoggerService.kt
  game/src/main/resources/log4j2.xml
Labels: enhancement, QA Testing, QA Approval

#573 Stairs
  data/cfg/stairs/stairs.json
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/draynor/morgans_house.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/falador/falador_castle.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/lumbridge_stairs.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/slayertower/stairs.plugin.kts
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/stairs/StairService.kt
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/stairs/Stairs.kt
  game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/stairs/stairs.plugin.kts
  game/src/main/kotlin/gg/rsmod/game/message/handler/OpLoc1Handler.kt
Labels: enhancement, content

#576 Server commands and Unix Domain Socket Listener
  build.gradle
  game/src/main/kotlin/gg/rsmod/game/Launcher.kt
  game/src/main/kotlin/gg/rsmod/game/Server.kt
Labels: content
